---
- hosts: all
  vars:
    docker_compose_version: "1.27.4"
    harbor_version: "v2.1.3"

    mirror_hostname: "dockerhub.stfc.ac.uk"
    harbor_hostname: "harbor.stfc.ac.uk"

    # Enable if deploying SSL certificates to host, otherwise disable
    host_ssl_termination: false

  tasks:
    # Uncomment to apt-get dist-upgrade and install fail2ban
    # - import_role: name=basic_ubuntu_setup
    #   become: yes

    # Since we need a frontend for harbor provided by the docker_cache layer
    # these are in the same playbook
    - import_role: name=docker_cache
      become: yes

    - import_role: name=harbor_server
      become: yes
